---
- hosts: all
  become: yes
  tasks:
    - name: Install Java and Maven
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openjdk-8-jdk
        - maven

    - name: Clone the repository
      git:
        repo: 'https://github.com/your-repo/spring-boot-app.git'
        dest: /home/ubuntu/spring-boot-app

    - name: Build the application with Maven
      command: mvn -f /home/ubuntu/spring-boot-app/pom.xml clean install

    - name: Copy WAR file to Tomcat
      copy:
        src: /home/ubuntu/spring-boot-app/target/your-app.war
        dest: /var/lib/tomcat8/webapps/your-app.war

    - name: Restart Tomcat
      service:
        name: tomcat8
        state: restarted
