---
- hosts: all
  become: yes
  tasks:
    - name: Copy WAR files to Jetty webapps directory
  copy:
    src: "{{ item }}"
    dest: /var/lib/jetty9/webapps/
  with_fileglob:
    - /tmp/jenkins/workspace/Build-and-Deploy/target/*.war


    - name: Restart Jetty
      service:
        name: jetty9
        state: restarted

    - name: Show public IP
      debug:
        msg: "Application is accessible at http://{{ ansible_host }}:8080"
