---
- hosts: all
  become: yes
  tasks:
    - name: Copy WAR file from Ansible controller to new instance
      copy:
        src: /tmp/jenkins/workspace/Build-and-Deploy/target/SpringMVCCRUDApp.war
        dest: /var/lib/jetty9/webapps/SpringMVCCRUDApp.war

    - name: Restart Jetty
      service:
        name: jetty9
        state: restarted

    - name: Show public IP
      debug:
        msg: "Application is accessible at http://{{ ansible_host }}:8080"
